# -*- coding: utf-8 -*-
"""
Recompute one-point-calibration validation results with precise time alignment.

Important:
1. The offline class models, priors, and hyperparameters are read from the
   Scheme-B JSON generated by scripts/train_all_models.py.
2. Online registration points are rebuilt from the current sliding-window
   persistence-time observations, and per-registration one-point adaptation is
   rerun using the saved offline models.
3. Temperature alignment uses the latest response timestamp in each five-sample
   window for the fused persistence-time observation.
4. All paths are resolved from the portable pypro project root.
"""

from __future__ import annotations

import importlib.util
import json
import math
import shutil
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

OLD_FASTREG_SCRIPT = PROJECT_ROOT / "src" / "fastreg_core.py"
TRAIN_DATA_PATH = PROJECT_ROOT / "data" / "training" / "studydata.txt"
FORMULA_PARAMS_PATH = PROJECT_ROOT / "outputs" / "offline_training" / "formula_params_studydata_8methods_schemeB.json"
REG_POINTS_FILE = PROJECT_ROOT / "data" / "validation" / "legacy_registration_points_not_used.csv"
DISCHARGE_DIR = PROJECT_ROOT / "data" / "validation" / "tags"
TEMP_CSV = PROJECT_ROOT / "data" / "temperature" / "123time_time_corrected.csv"

OUTPUT_ROOT = PROJECT_ROOT / "outputs"
OUTPUT_RESULT_ROOT = OUTPUT_ROOT / "results" / "fast_registration_precise_alignment"

HELPER_SCRIPT_CANDIDATES = [
    Path(__file__).resolve().parent / "01_sliding_window_vs_thermotag.py",
    Path.cwd() / "scripts" / "01_sliding_window_vs_thermotag.py",
]

BATCHES = [
    {"source_group": "C201", "batch": "Batch 2", "start": "C201", "end": "C230"},
    {"source_group": "C301", "batch": "Batch 3", "start": "C301", "end": "C330"},
    {"source_group": "C350", "batch": "Batch 4", "start": "C350", "end": "C379"},
]

EXPECTED_LEARNING_TAGS = 33
REPRESENTATIVE_FORMULA = "auto"

METHOD_TO_FORMULA = {
    "Paper": "f1",
    "M1": "f2",
    "M2": "f3",
    "M2pro": "f4",
    "EXP0": "f5",
    "EXP1": "f6",
    "EXP2": "f7",
    "EXP3": "f8",
}
FORMULA_TO_METHOD = {formula: method for method, formula in METHOD_TO_FORMULA.items()}
FORMULA_ORDER = [f"f{i}" for i in range(1, 9)]
METHOD_ORDER = [FORMULA_TO_METHOD[f] for f in FORMULA_ORDER]

TEMP_EDGES = np.array([10, 20, 30, 40, 50, 60, 70, 80], dtype=float)
TEMP_LABELS = [f"{int(TEMP_EDGES[i])}-{int(TEMP_EDGES[i + 1])}" for i in range(len(TEMP_EDGES) - 1)]

PAPER_LABEL_BASELINE = "ThermoTag-style baseline"

EXP_CLIP = 60.0
EXP_PMIN = 0.8
EXP_PMAX = 4.0
TMIN_NORM = -50.0
TMAX_NORM = 100.0
INVERSE_GRID_POINTS = 3001
INVERSE_T_GRID = np.linspace(TMIN_NORM, TMAX_NORM, INVERSE_GRID_POINTS)
INVERSE_X_GRID = np.clip((INVERSE_T_GRID - TMIN_NORM) / (TMAX_NORM - TMIN_NORM), 0.0, 1.0)


def reset_output_dirs() -> None:
    for folder in [OUTPUT_RESULT_ROOT]:
        if folder.exists():
            resolved = folder.resolve()
            root = OUTPUT_ROOT.resolve()
            if root not in resolved.parents and resolved != root:
                raise RuntimeError(f"Refusing to remove outside output root: {resolved}")
            shutil.rmtree(resolved)
        folder.mkdir(parents=True, exist_ok=True)


def load_python_module(path: Path, name: str):
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import module from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def load_helper_module():
    for candidate in HELPER_SCRIPT_CANDIDATES:
        if candidate.exists():
            return load_python_module(candidate, "sliding_window_helper")
    raise FileNotFoundError("Cannot find generate_sliding_window_vs_thermotag.py")


def parse_epc_num(epc: str) -> tuple[str, int]:
    text = str(epc).strip().upper()
    prefix = "".join(ch for ch in text if ch.isalpha())
    digits = "".join(ch for ch in text if ch.isdigit())
    return prefix, int(digits) if digits else -1


def tag_in_range(epc: str, start: str, end: str) -> bool:
    p, n = parse_epc_num(epc)
    p0, n0 = parse_epc_num(start)
    p1, n1 = parse_epc_num(end)
    return p == p0 == p1 and n0 <= n <= n1


def source_group_for_tag(epc: str) -> str:
    for info in BATCHES:
        if tag_in_range(epc, info["start"], info["end"]):
            return info["source_group"]
    return ""


def batch_label_for_source(source_group: str) -> str:
    for info in BATCHES:
        if info["source_group"] == source_group:
            return info["batch"]
    return str(source_group)


def all_validation_tags() -> list[str]:
    tags = []
    for info in BATCHES:
        p0, n0 = parse_epc_num(info["start"])
        _p1, n1 = parse_epc_num(info["end"])
        tags.extend([f"{p0}{n}" for n in range(n0, n1 + 1)])
    return tags


def method_to_formula(method: str) -> str:
    method = str(method).strip()
    return METHOD_TO_FORMULA.get(method, method)


def natural_key(text: str) -> tuple:
    import re

    parts = re.split(r"(\d+)", str(text))
    return tuple(int(part) if part.isdigit() else part for part in parts)


def build_sliding_window_cache(helper, tags: list[str]) -> dict[str, dict[str, Any]]:
    cache: dict[str, dict[str, Any]] = {}
    query_secs = []
    missing = []

    for tag in tags:
        if tag in cache:
            continue
        path = DISCHARGE_DIR / f"{tag}.csv"
        if not path.exists():
            missing.append(tag)
            continue
        _thermo, sliding = helper.load_tag_csv(path)
        sliding = sliding.sort_values("event_sec").reset_index(drop=True)
        cache[tag] = {"path": path, "sliding": sliding}
        if len(sliding):
            query_secs.append(sliding["event_sec"].to_numpy(dtype=float))

    if missing:
        raise FileNotFoundError(f"Missing discharge CSV for tags: {missing[:10]}")
    if not query_secs:
        raise RuntimeError("No valid sliding-window observations were loaded.")

    cache["_query_sec"] = {"values": np.concatenate(query_secs)}
    return cache


def read_temperature_pair(helper) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
    query_sec = TAG_CACHE["_query_sec"]["values"]
    temp_sec_raw, temp_val_raw = helper.read_temperature_csv(TEMP_CSV, smooth_window=1)
    temp_sec_eval, temp_val_eval = helper.read_temperature_csv(TEMP_CSV, smooth_window=helper.EVAL_TEMP_SMOOTH_WINDOW)
    shift = choose_precise_temperature_shift(helper, temp_sec_raw, temp_val_raw, query_sec)
    return temp_sec_raw + shift, temp_val_raw, temp_sec_eval + shift, temp_val_eval, float(shift)


def choose_precise_temperature_shift(helper, temp_sec: np.ndarray, temp_val: np.ndarray, query_sec: np.ndarray) -> float:
    """
    Choose the timestamp offset by actual nearest-record coverage.

    A long merged temperature log can span both old and new date ranges. Range
    overlap alone is therefore unsafe; the useful criterion is how many RFID
    query times can be matched to a real valid temperature sample within the
    interpolation gap threshold.
    """
    query_sec = np.asarray(query_sec, dtype=float)
    query_sec = query_sec[np.isfinite(query_sec)]
    if len(query_sec) == 0:
        return 0.0

    if len(query_sec) > 60000:
        step = int(math.ceil(len(query_sec) / 60000))
        sampled_query = query_sec[::step]
    else:
        sampled_query = query_sec

    offsets_days = [0, 365, 366, -365, -366, 730, 731, 732, -730, -731, -732]
    best_offset = 0.0
    best_score = (-1, -float("inf"))
    for days in offsets_days:
        offset = days * 86400.0
        matched = helper.interpolate_temperature(sampled_query, temp_sec + offset, temp_val)
        n_matched = int(np.isfinite(matched).sum())
        score = (n_matched, -abs(days))
        if score > best_score:
            best_score = score
            best_offset = offset

    return best_offset


def build_registration_points(helper, temp_sec_raw: np.ndarray, temp_val_raw: np.ndarray) -> list[dict[str, Any]]:
    rows = []
    reg_table_rows = []
    for tag in all_validation_tags():
        obs = TAG_CACHE[tag]["sliding"].copy()
        obs = obs[
            np.isfinite(obs["event_sec"])
            & np.isfinite(obs["persistence_time_s"])
            & (obs["persistence_time_s"] > helper.CURVE_TIME_MIN_S)
            & (obs["persistence_time_s"] < helper.CURVE_TIME_MAX_S)
        ].copy()
        obs = helper.local_outlier_filter(obs)
        obs["temperature_C"] = helper.interpolate_temperature(
            obs["event_sec"].to_numpy(dtype=float),
            temp_sec_raw,
            temp_val_raw,
        )
        obs = obs[np.isfinite(obs["temperature_C"])].copy()
        grouped = helper.group_curve_points(
            obs["temperature_C"].to_numpy(dtype=float),
            obs["persistence_time_s"].to_numpy(dtype=float),
        )
        grouped["temperature_C"] = pd.to_numeric(grouped["temperature_C"], errors="coerce")
        grouped["persistence_time_s"] = pd.to_numeric(grouped["persistence_time_s"], errors="coerce")
        grouped = grouped[
            np.isfinite(grouped["temperature_C"])
            & np.isfinite(grouped["persistence_time_s"])
            & (grouped["temperature_C"] >= TEMP_EDGES[0])
            & (grouped["temperature_C"] <= TEMP_EDGES[-1])
        ].copy()
        if len(grouped) < 5:
            raise RuntimeError(f"{tag} has too few registration points after grouping: {len(grouped)}")
        T = grouped["temperature_C"].to_numpy(dtype=float)
        y = grouped["persistence_time_s"].to_numpy(dtype=float)
        rows.append({"EPC": tag, "T": T, "y": y})
        for i, r in grouped.reset_index(drop=True).iterrows():
            reg_table_rows.append(
                {
                    "EPC": tag,
                    "source_group": source_group_for_tag(tag),
                    "batch": batch_label_for_source(source_group_for_tag(tag)),
                    "reg_idx": int(i + 1),
                    "T0": float(r["temperature_C"]),
                    "P0_s": float(r["persistence_time_s"]),
                    "n_points_in_temperature_bin": int(r.get("n_points", 0)),
                }
            )
    pd.DataFrame(reg_table_rows).to_csv(
        OUTPUT_RESULT_ROOT / "registration_points_sliding_window.csv",
        index=False,
        encoding="utf-8-sig",
    )
    return rows


def make_raw_eval_loader(helper, temp_sec_eval: np.ndarray, temp_val_eval: np.ndarray):
    def load_raw_eval_for_tag(reg_label: str, _discharge_dirs, _temp_sec, _temp_val):
        tag = str(reg_label).strip().upper()
        if tag not in TAG_CACHE:
            raise RuntimeError(f"No cached sliding-window observations for {tag}")
        obs = TAG_CACHE[tag]["sliding"].copy()
        obs["true_temperature_C"] = helper.interpolate_temperature(
            obs["event_sec"].to_numpy(dtype=float),
            temp_sec_eval,
            temp_val_eval,
        )
        good = (
            np.isfinite(obs["event_sec"])
            & np.isfinite(obs["persistence_time_s"])
            & np.isfinite(obs["true_temperature_C"])
            & (obs["persistence_time_s"] > 0)
            & (obs["persistence_time_s"] <= helper.EVAL_TIME_MAX_S)
        )
        obs = obs.loc[good].copy()
        if len(obs) < 5:
            raise RuntimeError(f"{tag} has too few valid evaluation points: {len(obs)}")

        return {
            "REG_LABEL": tag,
            "EPC": tag,
            "file": str(TAG_CACHE[tag]["path"]),
            "rfid_sec": obs["event_sec"].to_numpy(dtype=float),
            "T_true": obs["true_temperature_C"].to_numpy(dtype=float),
            "y_obs": obs["persistence_time_s"].to_numpy(dtype=float),
        }

    return load_raw_eval_for_tag


def fast_exp_ptag_vec(theta: dict[str, float], method: str, x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    g = (
        float(theta["a0"])
        + float(theta["a1"]) * x
        + float(theta["a2"]) * x * x
        + float(theta["a3"]) * x * x * x
    )
    pbase = EXP_PMIN + (EXP_PMAX - EXP_PMIN) / (1.0 + np.exp(-np.clip(g, -60.0, 60.0)))
    delta = float(theta.get("delta", 0.0))
    gamma = float(theta.get("gamma", 1.0))
    tau = float(theta.get("tau", 0.0))
    if method == "EXP0":
        ptag = pbase
    elif method == "EXP1":
        ptag = pbase + delta
    elif method == "EXP2":
        ptag = gamma * pbase + delta
    elif method == "EXP3":
        ptag = pbase + delta + tau * (x - 0.5)
    else:
        ptag = pbase
    return np.clip(ptag, EXP_PMIN, EXP_PMAX)


def fast_invert_exp(theta: dict[str, float], method: str, s: float, yobs: np.ndarray) -> np.ndarray:
    y = np.asarray(yobs, dtype=float)
    out = np.full_like(y, np.nan, dtype=float)
    if s <= 0:
        return out
    lam = float(theta["lambda"])
    B = float(theta["B"])
    if lam <= 0 or B <= 0:
        return out

    ptag = fast_exp_ptag_vec(theta, method, INVERSE_X_GRID)
    y_grid = s / (np.exp(np.clip(lam * (INVERSE_X_GRID ** ptag), -EXP_CLIP, EXP_CLIP)) + B)
    ok_grid = np.isfinite(y_grid)
    if ok_grid.sum() < 2:
        return out

    y_axis = y_grid[ok_grid][::-1]
    t_axis = INVERSE_T_GRID[ok_grid][::-1]
    keep = np.r_[True, np.diff(y_axis) > 1e-12]
    y_axis = y_axis[keep]
    t_axis = t_axis[keep]
    if len(y_axis) < 2:
        return out

    ok = np.isfinite(y) & (y > 0) & (y >= y_axis[0]) & (y <= y_axis[-1])
    out[ok] = np.interp(y[ok], y_axis, t_axis)
    return out


def patch_fastreg_module(mod) -> None:
    mod.RAW_DATA_PATH = str(TRAIN_DATA_PATH)
    mod.FORMULA_PARAMS_PATH = str(FORMULA_PARAMS_PATH)
    mod.TEMP_CSV_FILE = str(TEMP_CSV)
    mod.DISCHARGE_DIRS = [str(DISCHARGE_DIR)]
    mod.OUT_BASE_DIR = str(OUTPUT_RESULT_ROOT)
    mod.DEFAULT_T_EVAL_MIN = float(TEMP_EDGES[0])
    mod.DEFAULT_T_EVAL_MAX = float(TEMP_EDGES[-1])
    mod.EXCLUDE_REG_TEMP_WINDOW_C = 0.0
    mod.WRITE_RAW_DETAIL = False
    mod.WRITE_PER_TAG_FILES = False
    mod.invert_exp = fast_invert_exp


def theta_batch_from_q(method: str, q):
    import torch

    if method == "Paper":
        return {"b": torch.exp(q[:, 0]), "c": torch.exp(q[:, 1])}
    if method == "M1":
        return {"k": torch.exp(q[:, 0]), "b": torch.exp(q[:, 1])}
    if method == "M2":
        return {"lambda": torch.exp(q[:, 0]), "B": torch.exp(q[:, 1])}
    if method == "M2pro":
        sp = torch.sigmoid(q[:, 2])
        return {
            "lambda": torch.exp(q[:, 0]),
            "B": torch.exp(q[:, 1]),
            "p": 1.2 + (3.0 - 1.2) * sp,
        }

    th = {
        "lambda": torch.exp(q[:, 0]),
        "B": torch.exp(q[:, 1]),
        "a0": q[:, 2],
        "a1": q[:, 3],
        "a2": q[:, 4],
        "a3": q[:, 5],
    }
    if method == "EXP1":
        th["delta"] = -0.8 + 1.6 * torch.sigmoid(q[:, 6])
    elif method == "EXP2":
        th["delta"] = -0.8 + 1.6 * torch.sigmoid(q[:, 6])
        th["gamma"] = 0.6 + 0.8 * torch.sigmoid(q[:, 7])
    elif method == "EXP3":
        th["delta"] = -0.8 + 1.6 * torch.sigmoid(q[:, 6])
        th["tau"] = -1.0 + 2.0 * torch.sigmoid(q[:, 7])
    return th


def basis_batch_grid(method: str, th: dict[str, Any], T):
    import torch

    T = T.view(1, -1)
    if method == "Paper":
        z = torch.clamp(T / (th["c"].view(-1, 1) + 1e-12), -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.pow(torch.tensor(2.0, device=T.device), z) + th["b"].view(-1, 1))

    x = torch.clamp((T - TMIN_NORM) / (TMAX_NORM - TMIN_NORM), 0.0, 1.0)
    if method == "M1":
        z = torch.clamp(th["k"].view(-1, 1) * x, -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.pow(torch.tensor(2.0, device=T.device), z) + th["b"].view(-1, 1))
    if method == "M2":
        z = torch.clamp(th["lambda"].view(-1, 1) * x * x, -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.exp(z) + th["B"].view(-1, 1))
    if method == "M2pro":
        z = torch.clamp(th["lambda"].view(-1, 1) * torch.pow(x, th["p"].view(-1, 1)), -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.exp(z) + th["B"].view(-1, 1))

    g = (
        th["a0"].view(-1, 1)
        + th["a1"].view(-1, 1) * x
        + th["a2"].view(-1, 1) * x * x
        + th["a3"].view(-1, 1) * x * x * x
    )
    pbase = EXP_PMIN + (EXP_PMAX - EXP_PMIN) * torch.sigmoid(g)
    if method == "EXP0":
        ptag = pbase
    elif method == "EXP1":
        ptag = pbase + th["delta"].view(-1, 1)
    elif method == "EXP2":
        ptag = th["gamma"].view(-1, 1) * pbase + th["delta"].view(-1, 1)
    else:
        ptag = pbase + th["delta"].view(-1, 1) + th["tau"].view(-1, 1) * (x - 0.5)
    ptag = torch.clamp(ptag, EXP_PMIN, EXP_PMAX)
    z = torch.clamp(th["lambda"].view(-1, 1) * torch.pow(x, ptag), -EXP_CLIP, EXP_CLIP)
    return 1.0 / (torch.exp(z) + th["B"].view(-1, 1))


def basis_batch_row(method: str, th: dict[str, Any], T0):
    import torch

    if method == "Paper":
        z = torch.clamp(T0 / (th["c"] + 1e-12), -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.pow(torch.tensor(2.0, device=T0.device), z) + th["b"])

    x = torch.clamp((T0 - TMIN_NORM) / (TMAX_NORM - TMIN_NORM), 0.0, 1.0)
    if method == "M1":
        z = torch.clamp(th["k"] * x, -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.pow(torch.tensor(2.0, device=T0.device), z) + th["b"])
    if method == "M2":
        z = torch.clamp(th["lambda"] * x * x, -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.exp(z) + th["B"])
    if method == "M2pro":
        z = torch.clamp(th["lambda"] * torch.pow(x, th["p"]), -EXP_CLIP, EXP_CLIP)
        return 1.0 / (torch.exp(z) + th["B"])

    g = th["a0"] + th["a1"] * x + th["a2"] * x * x + th["a3"] * x * x * x
    pbase = EXP_PMIN + (EXP_PMAX - EXP_PMIN) * torch.sigmoid(g)
    if method == "EXP0":
        ptag = pbase
    elif method == "EXP1":
        ptag = pbase + th["delta"]
    elif method == "EXP2":
        ptag = th["gamma"] * pbase + th["delta"]
    else:
        ptag = pbase + th["delta"] + th["tau"] * (x - 0.5)
    ptag = torch.clamp(ptag, EXP_PMIN, EXP_PMAX)
    z = torch.clamp(th["lambda"] * torch.pow(x, ptag), -EXP_CLIP, EXP_CLIP)
    return 1.0 / (torch.exp(z) + th["B"])


def batch_adapt_theta(mod, method: str, ctx: dict[str, Any], reg_df: pd.DataFrame, device) -> tuple[pd.DataFrame, np.ndarray]:
    import torch

    n = len(reg_df)
    q0 = mod.q0_from_theta0(method, ctx["theta0"], device=device).float()
    q = torch.nn.Parameter(q0.view(1, -1).repeat(n, 1))
    opt = torch.optim.Adam([q], lr=float(getattr(mod, "ADAPT_LR", 0.06)))

    alpha_train = float(ctx["hp"]["alpha_train"])
    alpha_theta = float(ctx["hp"]["alpha_theta"])
    alpha_sprior = float(ctx["hp"]["alpha_sprior"])
    alpha_p = float(ctx["hp"].get("alpha_p", 0.0))
    alpha_smooth = float(ctx["hp"].get("alpha_smooth", 0.0))
    mu = torch.tensor(float(ctx["mu_log_s"]), dtype=torch.float32, device=device)
    sig = torch.tensor(float(max(ctx["sig_log_s"], 1e-6)), dtype=torch.float32, device=device)
    T0 = torch.tensor(reg_df["T0"].to_numpy(dtype=np.float32), dtype=torch.float32, device=device)
    y0 = torch.tensor(reg_df["y0"].to_numpy(dtype=np.float32), dtype=torch.float32, device=device)
    train_Ts = [torch.tensor(tg["T"], dtype=torch.float32, device=device) for tg in ctx["train_tags"]]
    train_ys = [torch.tensor(tg["y"], dtype=torch.float32, device=device) for tg in ctx["train_tags"]]

    for _ in range(int(getattr(mod, "ADAPT_ITERS", 80))):
        opt.zero_grad()
        th = theta_batch_from_q(method, q)
        train_sse = torch.zeros(n, dtype=torch.float32, device=device)
        for Ttr, ytr in zip(train_Ts, train_ys):
            b = torch.clamp(basis_batch_grid(method, th, Ttr), 1e-12, 1e12)
            ytr2 = ytr.view(1, -1)
            s_i = torch.sum(b * ytr2, dim=1) / (torch.sum(b * b, dim=1) + 1e-12)
            residual = ytr2 - s_i.view(-1, 1) * b
            train_sse = train_sse + torch.sum(residual * residual, dim=1)

        bas0 = torch.clamp(basis_batch_row(method, th, T0), 1e-12, 1e12)
        s_hat = torch.clamp(y0 / bas0, 1e-12, 1e18)
        loss_vec = (
            alpha_train * train_sse
            + alpha_theta * torch.sum((q - q0.view(1, -1)) * (q - q0.view(1, -1)), dim=1)
            + alpha_sprior * torch.pow((torch.log(s_hat) - mu) / sig, 2.0)
        )
        if method == "M2pro" and alpha_p > 0:
            loss_vec = loss_vec + alpha_p * torch.pow(th["p"] - 2.0, 2.0)
        if method.startswith("EXP") and alpha_smooth > 0:
            xg = torch.linspace(0.0, 1.0, steps=60, device=device).view(1, -1)
            g = (
                th["a0"].view(-1, 1)
                + th["a1"].view(-1, 1) * xg
                + th["a2"].view(-1, 1) * xg * xg
                + th["a3"].view(-1, 1) * xg * xg * xg
            )
            pbase = EXP_PMIN + (EXP_PMAX - EXP_PMIN) * torch.sigmoid(g)
            d2 = pbase[:, 2:] - 2.0 * pbase[:, 1:-1] + pbase[:, :-2]
            loss_vec = loss_vec + alpha_smooth * torch.sum(d2 * d2, dim=1)
        loss = torch.sum(loss_vec)
        if not torch.isfinite(loss).item():
            break
        loss.backward()
        opt.step()

    with torch.no_grad():
        th_final = theta_batch_from_q(method, q)
        bas0 = torch.clamp(basis_batch_row(method, th_final, T0), 1e-12, 1e12)
        s_hat_final = (y0 / bas0).detach().cpu().numpy().astype(float)
        theta_cols = {k: v.detach().cpu().numpy().astype(float) for k, v in th_final.items()}
    return pd.DataFrame(theta_cols), s_hat_final


def summarize_error_rows(rows: list[dict[str, Any]]) -> pd.DataFrame:
    df = pd.DataFrame(rows)
    out = []
    if df.empty:
        return pd.DataFrame()
    for (source_group, batch, epc, reg_label, method), g_all in df.groupby(["source_group", "batch", "EPC", "REG_LABEL", "method"]):
        g = g_all[g_all["status"].astype(str).str.upper() == "ACCEPT"].copy()
        g["MAE"] = pd.to_numeric(g["MAE"], errors="coerce")
        g["RMSE"] = pd.to_numeric(g["RMSE"], errors="coerce")
        g["MaxAE"] = pd.to_numeric(g["MaxAE"], errors="coerce")
        g_valid = g[np.isfinite(g["MAE"])].copy()
        if g_valid.empty:
            best = None
        else:
            best = g_valid.sort_values("MAE").iloc[0]
        out.append(
            {
                "source_group": source_group,
                "batch": batch,
                "EPC": epc,
                "REG_LABEL": reg_label,
                "method": method,
                "beta": "",
                "reg_points_total": int(len(g_all)),
                "reg_points_ACCEPT": int(len(g_valid)),
                "ACCEPT_rate": float(len(g_valid) / max(len(g_all), 1)),
                "MAE_over_ACCEPT_mean": "" if g_valid.empty else float(g_valid["MAE"].mean()),
                "RMSE_over_ACCEPT_mean": "" if g_valid.empty else float(g_valid["RMSE"].mean()),
                "MaxAE_over_ACCEPT_mean": "" if g_valid.empty else float(g_valid["MaxAE"].mean()),
                "best_reg_idx": "" if best is None else int(best["reg_idx"]),
                "best_T0": "" if best is None else float(best["T0"]),
                "best_y0": "" if best is None else float(best["y0"]),
                "best_MAE": "" if best is None else float(best["MAE"]),
                "best_RMSE": "" if best is None else float(best["RMSE"]),
                "best_MedianAE": "" if best is None else float(best["MedianAE"]),
                "best_P95AE": "" if best is None else float(best["P95AE"]),
                "best_MaxAE": "" if best is None else float(best["MaxAE"]),
                "best_Bias": "" if best is None else float(best["Bias"]),
                "best_objective": "" if best is None else float(best["MAE"]),
            }
        )
    return pd.DataFrame(out)


def run_fast_registration_batched(mod, reg_tags: list[dict[str, Any]], method_ctx, raw_loader) -> None:
    import torch

    device = torch.device("cpu")
    reg_rows = []
    for reg_tag in reg_tags:
        tag = str(reg_tag["EPC"]).upper()
        source_group = source_group_for_tag(tag)
        for idx, (T0, y0) in enumerate(zip(reg_tag["T"], reg_tag["y"]), start=1):
            reg_rows.append(
                {
                    "source_group": source_group,
                    "batch": batch_label_for_source(source_group),
                    "EPC": tag,
                    "REG_LABEL": tag,
                    "reg_idx": int(idx),
                    "T0": float(T0),
                    "y0": float(y0),
                    "raw_file": str(TAG_CACHE[tag]["path"]),
                }
            )
    reg_df = pd.DataFrame(reg_rows)

    eval_cache = {}
    for tag in all_validation_tags():
        raw = raw_loader(tag, None, None, None)
        T_raw = np.asarray(raw["T_true"], dtype=np.float64)
        y_raw = np.asarray(raw["y_obs"], dtype=np.float64)
        time_raw = np.asarray(raw["rfid_sec"], dtype=np.float64)
        mask = np.isfinite(T_raw) & np.isfinite(y_raw) & (T_raw >= TEMP_EDGES[0]) & (T_raw <= TEMP_EDGES[-1])
        eval_cache[tag] = {
            "T_true": T_raw[mask],
            "y_obs": y_raw[mask],
            "rfid_sec": time_raw[mask],
            "file": raw.get("file", ""),
        }

    all_errors: list[dict[str, Any]] = []
    all_params: list[dict[str, Any]] = []
    all_bins: list[dict[str, Any]] = []

    for method in METHOD_ORDER:
        ctx = method_ctx[method]
        theta_df, s_hat_arr = batch_adapt_theta(mod, method, ctx, reg_df, device)
        s_train = np.asarray(ctx["s_train"], dtype=np.float64)
        med_s = float(ctx["med_s"])
        mad_s = float(ctx["mad_s"])
        beta = float(ctx["beta"])

        for row_pos, row in reg_df.reset_index(drop=True).iterrows():
            tag = str(row["EPC"])
            raw = eval_cache[tag]
            T_true = raw["T_true"]
            y_obs = raw["y_obs"]
            n_eval = int(len(T_true))
            base = {
                "source_group": row["source_group"],
                "batch": row["batch"],
                "EPC": tag,
                "REG_LABEL": tag,
                "method": method,
                "formula": method_to_formula(method),
                "reg_idx": int(row["reg_idx"]),
                "T0": float(row["T0"]),
                "y0": float(row["y0"]),
                "raw_file": row["raw_file"],
            }
            theta = {col: float(theta_df.iloc[row_pos][col]) for col in theta_df.columns}
            s_hat = float(s_hat_arr[row_pos])
            param_row = dict(base)
            param_row.update({"s_hat": s_hat})
            param_row.update(theta)

            def add_reject(reason: str, zS: Any = "", zY: Any = "") -> None:
                err_row = dict(base)
                err_row.update(
                    {
                        "status": "REJECT",
                        "reason": reason,
                        "zS": zS,
                        "zY": zY,
                        "nEvalPts": n_eval,
                        "nPredValid": 0,
                        "validPredRatio": 0.0,
                        "MAE": "",
                        "RMSE": "",
                        "MedianAE": "",
                        "P95AE": "",
                        "MaxAE": "",
                        "Bias": "",
                    }
                )
                param_row.update({"status": "REJECT", "reason": reason, "zS": zS, "zY": zY})
                all_errors.append(err_row)
                all_params.append(dict(param_row))

            if n_eval == 0:
                add_reject("no_raw_eval_points")
                continue
            if (not np.isfinite(s_hat)) or s_hat <= 0:
                add_reject("invalid_s")
                continue

            zS = mod.z_robust_scalar(s_hat, med_s, mad_s)
            bas0 = mod.method_basis_np(method, ctx["theta0"], float(row["T0"]))
            if (not np.isfinite(bas0)) or bas0 <= 0 or s_train.size < 2:
                add_reject("basis0_invalid", zS=zS)
                continue
            y_train0 = s_train * bas0
            zY = mod.z_robust_scalar(float(row["y0"]), float(np.median(y_train0)), mod.robust_mad(y_train0))
            if abs(zS) > float(ctx["z_thresh_s"]) or abs(zY) > float(ctx["z_thresh_y"]):
                add_reject("z_outlier", zS=zS, zY=zY)
                continue

            T_hat = mod.method_invert_np(method, theta, s_hat, y_obs)
            metrics = mod.compute_error_metrics(T_hat, T_true)
            if metrics["nPredValid"] == 0:
                add_reject("invert_fail", zS=zS, zY=zY)
                continue

            err_row = dict(base)
            err_row.update({"status": "ACCEPT", "reason": "", "zS": zS, "zY": zY})
            err_row.update(metrics)
            all_errors.append(err_row)
            param_row.update({"status": "ACCEPT", "reason": "", "zS": zS, "zY": zY})
            all_params.append(dict(param_row))
            mod.add_tempbin_rows(all_bins, {**base, "status": "ACCEPT"}, T_hat, T_true)

    errors_df = pd.DataFrame(all_errors)
    params_df = pd.DataFrame(all_params)
    bins_df = pd.DataFrame(all_bins)

    for info in BATCHES:
        group_dir = OUTPUT_RESULT_ROOT / info["source_group"]
        group_dir.mkdir(parents=True, exist_ok=True)
        g_errors = errors_df[errors_df["source_group"] == info["source_group"]].copy()
        g_params = params_df[params_df["source_group"] == info["source_group"]].copy()
        g_bins = bins_df[bins_df["source_group"] == info["source_group"]].copy()
        g_summary = summarize_error_rows(g_errors.to_dict("records"))
        g_overall = mod.build_overall_summary(g_errors.to_dict("records"))
        g_errors.to_csv(group_dir / "all_tags_errors_points.csv", index=False, encoding="utf-8-sig")
        g_summary.to_csv(group_dir / "all_tags_errors_summary.csv", index=False, encoding="utf-8-sig")
        g_bins.to_csv(group_dir / "all_tags_errors_by_tempbin.csv", index=False, encoding="utf-8-sig")
        g_params.to_csv(group_dir / "all_tags_params_points.csv", index=False, encoding="utf-8-sig")
        mod.write_rows(str(group_dir / "all_methods_overall_summary.csv"), g_overall)
        mod.write_rows(str(group_dir / "all_methods_overall_summary_cn.csv"), mod.build_overall_summary_cn(g_overall))
        pd.DataFrame().to_csv(group_dir / "raw_point_filter_report.csv", index=False, encoding="utf-8-sig")

    combined_dir = OUTPUT_RESULT_ROOT / "C201_C301_C350_combined"
    combined_dir.mkdir(parents=True, exist_ok=True)
    summary_df = summarize_error_rows(errors_df.to_dict("records"))
    errors_df.to_csv(combined_dir / "all_tags_errors_points.csv", index=False, encoding="utf-8-sig")
    summary_df.to_csv(combined_dir / "all_tags_errors_summary.csv", index=False, encoding="utf-8-sig")
    bins_df.to_csv(combined_dir / "all_tags_errors_by_tempbin.csv", index=False, encoding="utf-8-sig")
    params_df.to_csv(combined_dir / "all_tags_params_points.csv", index=False, encoding="utf-8-sig")
    overall = mod.build_overall_summary(errors_df.to_dict("records"))
    mod.write_rows(str(combined_dir / "all_methods_overall_summary.csv"), overall)
    mod.write_rows(str(combined_dir / "all_methods_overall_summary_cn.csv"), mod.build_overall_summary_cn(overall))
    pd.DataFrame().to_csv(combined_dir / "raw_point_filter_report.csv", index=False, encoding="utf-8-sig")

    manifest = {
        "created_by": Path(__file__).name,
        "source_groups": [x["source_group"] for x in BATCHES],
        "output_group": combined_dir.name,
        "offline_model_source": "outputs/offline_training generated by train_all_models.py",
        "online_adaptation_rerun": True,
    }
    (combined_dir / "merge_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")


def run_fast_registration(mod, reg_tags: list[dict[str, Any]], method_ctx, temp_sec_eval, temp_val_eval) -> None:
    import torch

    device = torch.device("cpu")
    for info in BATCHES:
        mod.run_one_eval_group(
            group_name=info["source_group"],
            group_ranges=[(info["start"], info["end"])],
            reg_tags_all=reg_tags,
            method_ctx=method_ctx,
            temp_sec=temp_sec_eval,
            temp_val=temp_val_eval,
            T_eval_min=float(TEMP_EDGES[0]),
            T_eval_max=float(TEMP_EDGES[-1]),
            device=device,
        )


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame()
    try:
        return pd.read_csv(path, encoding="utf-8-sig")
    except pd.errors.EmptyDataError:
        return pd.DataFrame()


def merge_group_outputs(mod) -> None:
    combined_dir = OUTPUT_RESULT_ROOT / "C201_C301_C350_combined"
    combined_dir.mkdir(parents=True, exist_ok=True)

    table_names = [
        "all_tags_errors_points.csv",
        "all_tags_errors_summary.csv",
        "all_tags_errors_by_tempbin.csv",
        "all_tags_params_points.csv",
        "raw_point_filter_report.csv",
    ]

    combined_error_rows = []
    for table_name in table_names:
        frames = []
        for info in BATCHES:
            path = OUTPUT_RESULT_ROOT / info["source_group"] / table_name
            df = read_csv(path)
            if df.empty:
                continue
            df.insert(0, "batch", info["batch"])
            df.insert(0, "source_group", info["source_group"])
            frames.append(df)
            if table_name == "all_tags_errors_points.csv":
                combined_error_rows.extend(df.to_dict("records"))
        out = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
        out.to_csv(combined_dir / table_name, index=False, encoding="utf-8-sig")

    overall = mod.build_overall_summary(combined_error_rows)
    mod.write_rows(str(combined_dir / "all_methods_overall_summary.csv"), overall)
    mod.write_rows(str(combined_dir / "all_methods_overall_summary_cn.csv"), mod.build_overall_summary_cn(overall))

    manifest = {
        "created_by": Path(__file__).name,
        "source_groups": [x["source_group"] for x in BATCHES],
        "output_group": combined_dir.name,
        "note": "Merged from precise-alignment fast-registration validation outputs. Offline class-model training was not rerun.",
    }
    (combined_dir / "merge_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")


def accepted_mask(df: pd.DataFrame) -> pd.Series:
    if "status" not in df.columns:
        return pd.Series(True, index=df.index)
    return df["status"].astype(str).str.strip().str.upper().eq("ACCEPT")


def to_numeric(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    out = df.copy()
    for col in cols:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")
    return out


def weighted_mean(values: pd.Series, weights: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce").to_numpy(dtype=float)
    w = pd.to_numeric(weights, errors="coerce").to_numpy(dtype=float)
    ok = np.isfinite(v) & np.isfinite(w) & (w > 0)
    if not np.any(ok):
        return float("nan")
    return float(np.sum(v[ok] * w[ok]) / np.sum(w[ok]))


def sample_std(values: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce").to_numpy(dtype=float)
    v = v[np.isfinite(v)]
    if len(v) <= 1:
        return 0.0 if len(v) == 1 else float("nan")
    return float(np.std(v, ddof=1))


def assign_temp_bin(values: pd.Series) -> pd.Series:
    x = pd.to_numeric(values, errors="coerce")
    labels = pd.cut(x, bins=TEMP_EDGES, labels=TEMP_LABELS, right=False, include_lowest=True)
    labels = labels.astype(object)
    labels.loc[x == TEMP_EDGES[-1]] = TEMP_LABELS[-1]
    return labels


def empirical_cdf(values: pd.Series | np.ndarray) -> pd.DataFrame:
    arr = np.asarray(values, dtype=float)
    arr = np.sort(arr[np.isfinite(arr)])
    if len(arr) == 0:
        return pd.DataFrame({"error_C": [], "cdf": []})
    return pd.DataFrame({"error_C": arr, "cdf": np.arange(1, len(arr) + 1) / len(arr)})


def fit_mean_parameter_thermotag(
    helper,
    train_tags: list[dict[str, Any]],
) -> tuple[float, float, float, pd.DataFrame]:
    expected_epcs = {f"C{i}" for i in range(250, 283)}
    actual_epcs = {str(tag["EPC"]).upper() for tag in train_tags}
    if len(train_tags) != EXPECTED_LEARNING_TAGS or actual_epcs != expected_epcs:
        raise RuntimeError(
            "ThermoTag baseline requires exactly the 33 learning tags C250-C282; "
            f"received {len(train_tags)} tags: {sorted(actual_epcs, key=natural_key)}"
        )

    fit_rows: list[dict[str, Any]] = []
    for tag in sorted(train_tags, key=lambda item: natural_key(str(item["EPC"]))):
        epc = str(tag["EPC"]).upper()
        temperature = np.asarray(tag["T"], dtype=float)
        persistence_time = np.asarray(tag["y"], dtype=float)
        if temperature.shape != persistence_time.shape:
            raise RuntimeError(f"Mismatched temperature/persistence arrays for {epc}.")
        fit = helper.fit_abc(temperature, persistence_time)
        fit_rows.append(
            {
                "EPC": epc,
                "a": float(fit["a"]),
                "b": float(fit["b"]),
                "c": float(fit["c"]),
                "curve_rmse_s": float(fit["curve_rmse_s"]),
                "curve_r2": float(fit["curve_r2"]),
                "n_curve_points": int(fit["n_curve_points"]),
                "temperature_min_C": float(np.min(temperature)),
                "temperature_max_C": float(np.max(temperature)),
            }
        )

    learning_fits = pd.DataFrame(fit_rows)
    means = learning_fits[["a", "b", "c"]].mean(axis=0)
    if not np.all(np.isfinite(means.to_numpy(dtype=float))):
        raise RuntimeError("Non-finite mean ThermoTag parameters from the 33 learning tags.")
    learning_fits.to_csv(
        OUTPUT_RESULT_ROOT / "thermotag_mean_parameter_learning_tag_fits.csv",
        index=False,
        encoding="utf-8-sig",
    )
    return float(means["a"]), float(means["b"]), float(means["c"]), learning_fits


def build_thermotag_mean_parameter_baseline(
    helper,
    train_tags: list[dict[str, Any]],
    temp_sec_eval: np.ndarray,
    temp_val_eval: np.ndarray,
):
    a, b, c, learning_fits = fit_mean_parameter_thermotag(helper, train_tags)
    point_frames = []
    failures = []

    for tag in all_validation_tags():
        source_group = source_group_for_tag(tag)
        obs = TAG_CACHE[tag]["sliding"].copy()
        obs["true_temp_C"] = helper.interpolate_temperature(
            obs["event_sec"].to_numpy(dtype=float),
            temp_sec_eval,
            temp_val_eval,
        )
        obs = obs[
            np.isfinite(obs["true_temp_C"])
            & (obs["true_temp_C"] >= TEMP_EDGES[0])
            & (obs["true_temp_C"] <= TEMP_EDGES[-1])
            & np.isfinite(obs["persistence_time_s"])
            & (obs["persistence_time_s"] > 0)
            & (obs["persistence_time_s"] <= helper.EVAL_TIME_MAX_S)
        ].copy()
        if obs.empty:
            failures.append({"tag": tag, "source_group": source_group, "error": "no valid evaluation points"})
            continue
        pred = helper.inverse_temperature(obs["persistence_time_s"].to_numpy(dtype=float), a, b, c)
        ok = np.isfinite(pred)
        obs = obs.loc[ok].copy()
        pred = pred[ok]
        if obs.empty:
            failures.append({"tag": tag, "source_group": source_group, "error": "no valid inverse-temperature predictions"})
            continue
        obs["tag"] = tag
        obs["source_group"] = source_group
        obs["batch"] = batch_label_for_source(source_group)
        obs["method"] = PAPER_LABEL_BASELINE
        obs["rfid_sec"] = obs["event_sec"].to_numpy(dtype=float)
        obs["fused_time_s"] = obs["persistence_time_s"].to_numpy(dtype=float)
        obs["pred_temp_C"] = pred
        obs["signed_error_C"] = obs["pred_temp_C"] - obs["true_temp_C"]
        obs["abs_error_C"] = np.abs(obs["signed_error_C"])
        obs["temp_bin"] = assign_temp_bin(obs["true_temp_C"])
        point_frames.append(
            obs[
                [
                    "source_group",
                    "batch",
                    "tag",
                    "rfid_sec",
                    "true_temp_C",
                    "fused_time_s",
                    "pred_temp_C",
                    "signed_error_C",
                    "abs_error_C",
                    "method",
                    "temp_bin",
                ]
            ]
        )

    points = pd.concat(point_frames, ignore_index=True) if point_frames else pd.DataFrame()
    points.to_csv(OUTPUT_RESULT_ROOT / "thermotag_mean_parameter_point_errors.csv", index=False, encoding="utf-8-sig")

    per_tag_rows = []
    for (source_group, batch, tag), d in points.groupby(["source_group", "batch", "tag"]):
        err = d["signed_error_C"].to_numpy(dtype=float)
        ae = np.abs(err)
        per_tag_rows.append(
            {
                "source_group": source_group,
                "batch": batch,
                "tag": tag,
                "n_points": int(len(d)),
                "mean_error_C": float(np.mean(ae)),
                "rmse_error_C": float(np.sqrt(np.mean(err * err))),
                "median_error_C": float(np.median(ae)),
                "p95_error_C": float(np.percentile(ae, 95)),
                "max_error_C": float(np.max(ae)),
                "bias_C": float(np.mean(err)),
            }
        )
    per_tag = pd.DataFrame(per_tag_rows)
    per_tag.to_csv(OUTPUT_RESULT_ROOT / "thermotag_mean_parameter_per_tag_summary.csv", index=False, encoding="utf-8-sig")

    temp_rows = []
    for label in TEMP_LABELS:
        d = points[points["temp_bin"].astype(str) == label]
        err = d["signed_error_C"].to_numpy(dtype=float) if len(d) else np.array([])
        ae = np.abs(err)
        temp_rows.append(
            {
                "method": PAPER_LABEL_BASELINE,
                "temp_bin": label,
                "n_points": int(len(d)),
                "n_tags": int(d["tag"].nunique()) if len(d) else 0,
                "mean_error_C": float(np.mean(ae)) if len(ae) else float("nan"),
                "std_error_C": float(np.std(ae, ddof=1)) if len(ae) > 1 else (0.0 if len(ae) == 1 else float("nan")),
                "rmse_error_C": float(np.sqrt(np.mean(err * err))) if len(err) else float("nan"),
            }
        )
    tempbin = pd.DataFrame(temp_rows)
    tempbin.to_csv(OUTPUT_RESULT_ROOT / "thermotag_mean_parameter_tempbin_summary.csv", index=False, encoding="utf-8-sig")

    meta = {
        "learning_tag_count": int(len(learning_fits)),
        "learning_tags": learning_fits["EPC"].tolist(),
        "mean_a": a,
        "mean_b": b,
        "mean_c": c,
        "parameter_aggregation": "Arithmetic mean of parameters fitted separately to the complete multi-temperature data of each learning tag.",
        "individual_fit_file": "thermotag_mean_parameter_learning_tag_fits.csv",
        "mean_learning_fit_R2": float(learning_fits["curve_r2"].mean()),
        "minimum_learning_fit_R2": float(learning_fits["curve_r2"].min()),
        "baseline_definition": "ThermoTag model formed by averaging the separately fitted a, b, and c parameters of learning tags C250-C282 and applying the fixed shared model to all validation tags.",
        "failures": failures,
    }
    (OUTPUT_RESULT_ROOT / "thermotag_mean_parameter_model_info.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return points, per_tag, tempbin


def normalize_temp_bin_label(value: Any) -> str:
    text = str(value).strip().replace("_", "-")
    text = text.replace("°C", "").replace(" ", "")
    return text


def build_paper_tables(thermotag_points: pd.DataFrame, thermotag_tempbin: pd.DataFrame) -> dict[str, pd.DataFrame]:
    combined_dir = OUTPUT_RESULT_ROOT / "C201_C301_C350_combined"
    err_points = to_numeric(read_csv(combined_dir / "all_tags_errors_points.csv"), ["MAE", "RMSE", "MedianAE", "P95AE", "MaxAE", "Bias", "nEvalPts", "nPredValid", "T0"])
    err_summary = to_numeric(read_csv(combined_dir / "all_tags_errors_summary.csv"), ["MAE_over_ACCEPT_mean", "ACCEPT_rate"])
    tempbin_rows = to_numeric(read_csv(combined_dir / "all_tags_errors_by_tempbin.csv"), ["MAE", "RMSE", "nPredValid", "nEvalPts", "bin_start", "bin_end"])

    err_points["formula"] = err_points["method"].map(METHOD_TO_FORMULA)
    err_summary["formula"] = err_summary["method"].map(METHOD_TO_FORMULA)
    tempbin_rows["formula"] = tempbin_rows["method"].map(METHOD_TO_FORMULA)
    err_points["accepted"] = accepted_mask(err_points)
    accepted = err_points[err_points["accepted"] & np.isfinite(err_points["MAE"])].copy()

    formula_rows = []
    for formula in FORMULA_ORDER:
        method = FORMULA_TO_METHOD[formula]
        g_all = err_points[err_points["method"] == method]
        g = accepted[accepted["method"] == method]
        formula_rows.append(
            {
                "formula": formula,
                "method_internal": method,
                "n_tags": int(g["EPC"].nunique()),
                "n_registration_trials_total": int(len(g_all)),
                "n_registration_trials_accepted": int(len(g)),
                "acceptance_rate": float(len(g) / len(g_all)) if len(g_all) else float("nan"),
                "mean_registration_MAE_C": float(g["MAE"].mean()) if len(g) else float("nan"),
                "std_registration_MAE_C": sample_std(g["MAE"]),
                "median_registration_MAE_C": float(g["MAE"].median()) if len(g) else float("nan"),
                "p95_registration_MAE_C": float(np.percentile(g["MAE"], 95)) if len(g) else float("nan"),
                "weighted_mean_registration_MAE_C": weighted_mean(g["MAE"], g["nPredValid"]) if len(g) else float("nan"),
                "mean_registration_RMSE_C": float(g["RMSE"].mean()) if len(g) else float("nan"),
            }
        )
    formula_summary = pd.DataFrame(formula_rows)
    formula_summary.to_csv(OUTPUT_RESULT_ROOT / "01_formula_summary_all_batches.csv", index=False, encoding="utf-8-sig")

    if REPRESENTATIVE_FORMULA == "auto":
        representative_formula = str(formula_summary.sort_values("weighted_mean_registration_MAE_C").iloc[0]["formula"])
    else:
        representative_formula = REPRESENTATIVE_FORMULA
    representative_method = FORMULA_TO_METHOD[representative_formula]

    batch_rows = []
    for info in BATCHES:
        g = accepted[(accepted["method"] == representative_method) & (accepted["source_group"] == info["source_group"])]
        batch_rows.append(
            {
                "batch": info["batch"],
                "source_group": info["source_group"],
                "formula": representative_formula,
                "n_tags": int(g["EPC"].nunique()),
                "n_registration_trials": int(len(g)),
                "mean_registration_MAE_C": float(g["MAE"].mean()) if len(g) else float("nan"),
                "std_registration_MAE_C": sample_std(g["MAE"]),
                "median_registration_MAE_C": float(g["MAE"].median()) if len(g) else float("nan"),
                "p95_registration_MAE_C": float(np.percentile(g["MAE"], 95)) if len(g) else float("nan"),
            }
        )
    batch_summary = pd.DataFrame(batch_rows)
    batch_summary.to_csv(OUTPUT_RESULT_ROOT / "02_batch_summary_representative_formula.csv", index=False, encoding="utf-8-sig")

    regtemp_rows = []
    accepted["registration_temp_bin"] = assign_temp_bin(accepted["T0"])
    for batch in [x["batch"] for x in BATCHES]:
        for formula in FORMULA_ORDER:
            for label in TEMP_LABELS:
                g = accepted[(accepted["batch"] == batch) & (accepted["formula"] == formula) & (accepted["registration_temp_bin"].astype(str) == label)]
                regtemp_rows.append(
                    {
                        "batch": batch,
                        "formula": formula,
                        "registration_temp_bin": label,
                        "registration_temp_center_C": 0.5 * (float(label.split("-")[0]) + float(label.split("-")[1])),
                        "n_registration_trials": int(len(g)),
                        "n_tags": int(g["EPC"].nunique()) if len(g) else 0,
                        "mean_registration_MAE_C": float(g["MAE"].mean()) if len(g) else float("nan"),
                        "std_registration_MAE_C": sample_std(g["MAE"]),
                        "median_registration_MAE_C": float(g["MAE"].median()) if len(g) else float("nan"),
                        "p95_registration_MAE_C": float(np.percentile(g["MAE"], 95)) if len(g) else float("nan"),
                    }
                )
    regtemp_summary = pd.DataFrame(regtemp_rows)
    regtemp_summary.to_csv(OUTPUT_RESULT_ROOT / "04_registration_temperature_summary.csv", index=False, encoding="utf-8-sig")

    tempbin_rows = tempbin_rows[accepted_mask(tempbin_rows) & (tempbin_rows["method"] == representative_method)].copy()
    tempbin_rows["temp_bin_norm"] = tempbin_rows["temp_bin"].map(normalize_temp_bin_label)
    proposed_temp_rows = []
    for label in TEMP_LABELS:
        g = tempbin_rows[tempbin_rows["temp_bin_norm"] == label]
        proposed_temp_rows.append(
            {
                "method": f"Proposed ({representative_formula})",
                "temp_bin": label,
                "n_points": int(pd.to_numeric(g["nPredValid"], errors="coerce").fillna(0).sum()) if len(g) else 0,
                "n_tags": int(g["EPC"].nunique()) if len(g) else 0,
                "mean_error_C": weighted_mean(g["MAE"], g["nPredValid"]) if len(g) else float("nan"),
                "std_error_C": sample_std(g["MAE"]),
                "rmse_error_C": weighted_mean(g["RMSE"], g["nPredValid"]) if len(g) else float("nan"),
            }
        )
    proposed_tempbin = pd.DataFrame(proposed_temp_rows)
    tempbin_compare = pd.concat([thermotag_tempbin, proposed_tempbin], ignore_index=True)
    tempbin_compare.to_csv(OUTPUT_RESULT_ROOT / "03_tempbin_summary_thermotag_vs_fastreg.csv", index=False, encoding="utf-8-sig")

    cdf_rows = []
    base_cdf = empirical_cdf(thermotag_points["abs_error_C"])
    base_cdf.insert(0, "method", PAPER_LABEL_BASELINE)
    cdf_rows.append(base_cdf)
    prop_cdf = empirical_cdf(accepted[accepted["formula"] == representative_formula]["MAE"])
    prop_cdf.insert(0, "method", f"Proposed ({representative_formula})")
    cdf_rows.append(prop_cdf)
    cdf_compare = pd.concat(cdf_rows, ignore_index=True)
    cdf_compare.to_csv(OUTPUT_RESULT_ROOT / "07_thermotag_vs_fastreg_cdf_data.csv", index=False, encoding="utf-8-sig")

    batch_cdf_rows = []
    for batch in [x["batch"] for x in BATCHES]:
        cdf = empirical_cdf(accepted[(accepted["batch"] == batch) & (accepted["formula"] == representative_formula)]["MAE"])
        cdf.insert(0, "batch", batch)
        cdf.insert(0, "formula", representative_formula)
        batch_cdf_rows.append(cdf)
    batch_cdf = pd.concat(batch_cdf_rows, ignore_index=True)
    batch_cdf.to_csv(OUTPUT_RESULT_ROOT / "08_fastreg_batch_cdf_data.csv", index=False, encoding="utf-8-sig")

    reject_rows = []
    rejects = err_points[~err_points["accepted"]].copy()
    if not rejects.empty:
        for (batch, formula, epc), g in rejects.groupby(["batch", "formula", "EPC"]):
            tags_in_batch = [t for t in all_validation_tags() if batch_label_for_source(source_group_for_tag(t)) == batch]
            reject_rows.append(
                {
                    "batch": batch,
                    "tag_order_in_batch": tags_in_batch.index(epc) + 1 if epc in tags_in_batch else "",
                    "formula": formula,
                    "n_rejected_registration_points": int(len(g)),
                }
            )
    reject_trace = pd.DataFrame(reject_rows).sort_values(["batch", "tag_order_in_batch", "formula"]) if reject_rows else pd.DataFrame(
        columns=["batch", "tag_order_in_batch", "formula", "n_rejected_registration_points"]
    )
    reject_trace.to_csv(OUTPUT_RESULT_ROOT / "09_reject_traceable_without_epc.csv", index=False, encoding="utf-8-sig")

    heat = (
        err_summary.pivot_table(
            index="EPC",
            columns="formula",
            values="MAE_over_ACCEPT_mean",
            aggfunc="mean",
            observed=False,
        )
        .reindex(columns=FORMULA_ORDER)
    )
    heat = heat.reindex(index=sorted(heat.index, key=natural_key))
    heat.to_csv(OUTPUT_RESULT_ROOT / "05_formula_tag_mae_matrix.csv", encoding="utf-8-sig")

    meta = {
        "representative_formula": representative_formula,
        "representative_method_internal": representative_method,
        "baseline_label": PAPER_LABEL_BASELINE,
    }
    (OUTPUT_RESULT_ROOT / "paper_table_info.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

    return {
        "formula_summary": formula_summary,
        "batch_summary": batch_summary,
        "regtemp_summary": regtemp_summary,
        "tempbin_compare": tempbin_compare,
        "cdf_compare": cdf_compare,
        "batch_cdf": batch_cdf,
        "reject_trace": reject_trace,
        "heatmap": heat,
        "representative_formula": representative_formula,
    }


TAG_CACHE: dict[str, dict[str, Any]] = {}


def main() -> None:
    if not FORMULA_PARAMS_PATH.exists():
        raise FileNotFoundError(
            f"Missing trained model: {FORMULA_PARAMS_PATH}. "
            "Run scripts/train_all_models.py before one-point evaluation."
        )
    reset_output_dirs()

    helper = load_helper_module()
    fastreg = load_python_module(OLD_FASTREG_SCRIPT, "fastreg_old_logic")
    patch_fastreg_module(fastreg)

    tags = all_validation_tags()
    global TAG_CACHE
    TAG_CACHE = build_sliding_window_cache(helper, tags)

    temp_sec_raw, temp_val_raw, temp_sec_eval, temp_val_eval, temp_shift = read_temperature_pair(helper)
    reg_tags = build_registration_points(helper, temp_sec_raw, temp_val_raw)

    with FORMULA_PARAMS_PATH.open("r", encoding="utf-8") as handle:
        params = json.load(handle)
    train_tags = fastreg.load_tags_from_txt(str(TRAIN_DATA_PATH))
    epc2tag = {str(tg["EPC"]).upper(): tg for tg in train_tags}
    epc2tag.update({str(tg["EPC"]): tg for tg in train_tags})
    method_ctx = fastreg.prepare_method_contexts(params, epc2tag)

    raw_loader = make_raw_eval_loader(helper, temp_sec_eval, temp_val_eval)
    fastreg.load_raw_eval_for_tag = raw_loader
    run_fast_registration_batched(fastreg, reg_tags, method_ctx, raw_loader)

    thermotag_points, _thermotag_per_tag, thermotag_tempbin = build_thermotag_mean_parameter_baseline(
        helper,
        train_tags,
        temp_sec_eval,
        temp_val_eval,
    )
    tables = build_paper_tables(thermotag_points, thermotag_tempbin)

    run_info = {
        "created_by": Path(__file__).name,
        "offline_model_source": "outputs/offline_training generated by train_all_models.py",
        "online_adaptation_rerun": True,
        "online_objective": "training consistency + class-model distance + scale prior + formula-specific regularization",
        "formula_specific_regularization": {
            "f4": "alpha_p * (p - 2)^2",
            "f5_to_f8": "alpha_smooth * sum(second_difference(pbase)^2)",
        },
        "registration_points_source": "rebuilt from sliding-window persistence-time observations",
        "offline_formula_params": str(FORMULA_PARAMS_PATH),
        "offline_learning_data": str(TRAIN_DATA_PATH),
        "legacy_registration_points_file_not_used": str(REG_POINTS_FILE),
        "discharge_dir": str(DISCHARGE_DIR),
        "temperature_csv": str(TEMP_CSV),
        "output_result_root": str(OUTPUT_RESULT_ROOT),
        "validation_tags": len(tags),
        "temperature_time_shift_seconds": temp_shift,
        "temperature_alignment": "Each sliding-window persistence-time observation is aligned to the latest response timestamp in the five-sample window.",
        "registration_points": "Rebuilt from validation-tag sliding-window persistence-time observations; see registration_points_sliding_window.csv.",
        "evaluation_points": "Rebuilt from validation tags using sliding-window persistence-time observations and latest-response timestamp alignment.",
        "representative_formula": tables["representative_formula"],
        "thermotag_baseline": "Fixed ThermoTag-style model formed by averaging a, b, and c fitted separately from the complete multi-temperature data of learning tags C250-C282, then applied to all validation tags using the same sliding-window persistence-time observations.",
    }
    (OUTPUT_RESULT_ROOT / "run_info.json").write_text(json.dumps(run_info, ensure_ascii=False, indent=2), encoding="utf-8")

    print("Finished one-point-calibration precise-alignment recomputation.")
    print(f"Results: {OUTPUT_RESULT_ROOT}")
    print(f"Representative formula: {tables['representative_formula']}")
    print()
    print(tables["formula_summary"].to_string(index=False))
    print()
    print(tables["tempbin_compare"].to_string(index=False))
    if not tables["reject_trace"].empty:
        print()
        print(tables["reject_trace"].to_string(index=False))


if __name__ == "__main__":
    main()
